const TEMPLATE = 'TEMPLATE'
const CHANGE_USERINFO = 'CHANGE_USERINFO'
const GET_USERNAME = 'GET_USERNAME'
const EXIT_USERINFO = 'EXIT_USERINFO'

export {
    TEMPLATE,CHANGE_USERINFO,GET_USERNAME,EXIT_USERINFO
}